### ISSUE TITLE
Undefined reference to static thread_local struct member in shared library

### ISSUE THREAD

**Issue by peterazmanov** [yrnkrn/zapcc#21]
Stumbled upon this issue trying to compile some code which uses [fbthrift](https://github.com/facebook/fbthrift). I managed to reproduce the issue with the following simple test case.

a_lib.h:
```C++
struct A
{
  A()
  {
    tm = 0;
  }

  static thread_local int tm;
};
```
a_lib.cpp:
```C++
#include "a_lib.h"

thread_local int A::tm;
```
main.cpp:
```c++
#include "a_lib.h"

int main()
{
  A a;
  return 0;
}
```
build_zapcc.sh:
```bash
#!/bin/bash -e

zapcc++ -c -fPIC a_lib.cpp
zapcc++ -fPIC a_lib.o -shared -o a_lib.so

zapcc++ main.cpp a_lib.so
```
Output:
```
/tmp/main-62d36d.o: In function `A::A()':
main.cpp:(.text._ZN1AC2Ev[_ZN1AC2Ev]+0xd): undefined reference to `TLS wrapper function for A::tm'
zapcc: error: linker command failed with exit code 1 (use -v to see invocation)
```
Test compiles fine with GCC 8.1.1, Clang 6.0 and Clang 7.0 (svn_r338211).

[thread_local_test.zip](https://github.com/yrnkrn/zapcc/files/2249205/thread_local_test.zip)

**Comment by yrnkrn** [comment]
Thanks, I'll look into this.

**Comment by yrnkrn** [comment]
One-file example, no caching.
[21.zip](https://github.com/yrnkrn/zapcc/files/2257635/21.zip)

**Comment by yrnkrn** [comment]
Fixed in 57f48831bf15a2d9440167d272196f3626d1e43f
